### ISSUE TITLE
Great work, when will the code be released？

### ISSUE THREAD

**Issue by zhanghongyong123456** [Picsart-AI-Research/StreamingT2V#1]

**Comment by vgarleanu** [comment]
+1 on this. Are there any plans to release the source code?

**Comment by howardgriffin** [comment]
+1

**Comment by zx377262372** [comment]
+1

**Comment by mumianyuxin** [comment]
+1

**Comment by LeonLIU08** [comment]
+1

**Comment by ninjasaid2k** [comment]
+1

**Comment by veryVANYA** [comment]
+100

**Comment by nemonameless** [comment]
@levon-khachatryan @honghuis  Could you please give an approximate time ? thanks

**Comment by honghuis** [comment]
Hey, thanks for your interest, we are preparing the code/demo and resolving a few open-source licensing issues and hope to release a first version within two weeks if not sooner )
