### ISSUE TITLE
[bug] in inference.py

### ISSUE THREAD

**Issue by FEIFEIEIAr** [Picsart-AI-Research/StreamingT2V#14]
When I run the code, following error occurred.
```
Traceback (most recent call last):
  File "/home/StreamingT2V/t2v_enhanced/inference.py", line 97, in <module>
    stream_long_gen(args.prompt, short_video, n_autoreg_gen, args.negative_prompt, args.seed, args.num_steps, args.image_guidance, name, stream_cli, stream_model)
TypeError: stream_long_gen() takes 9 positional arguments but 10 were given
```
In `infernece.py` 10 parameters are passed in.
```
stream_long_gen(args.prompt, short_video, n_autoreg_gen, args.negative_prompt, args.seed, args.num_steps, args.image_guidance, name, stream_cli, stream_model)
```
However, when `stream_long_gen` is defined only 9 parameters there.
```
def stream_long_gen(prompt, short_video, n_autoreg_gen, seed, t, image_guidance, result_file_stem, stream_cli, stream_model):
```

**Comment by oldnaari** [comment]
Hi @FEIFEIEIAr. Thank you for your feedback. We are currently working on the proper solution. Meanwhile as a quick fix please remove args.negative_prompt in the line 
https://github.com/Picsart-AI-Research/StreamingT2V/blob/2d3b22107004695871ba297efa7e53f40f8f8e77/t2v_enhanced/inference.py#L97

**Comment by oldnaari** [comment]
Hi @FEIFEIEIAr. Thank you for your feedback. We are currently working on the proper solution. 
Meanwhile for everyone with this issue removing args.negative_prompt in the line 
https://github.com/Picsart-AI-Research/StreamingT2V/blob/2d3b22107004695871ba297efa7e53f40f8f8e77/t2v_enhanced/inference.py#L97
should fix it. Sorry for the inconvenience

**Comment by oldnaari** [comment]
Should be fixed by https://github.com/Picsart-AI-Research/StreamingT2V/pull/16 https://github.com/Picsart-AI-Research/StreamingT2V/pull/15
