### ISSUE TITLE
Great Work, will you release the MAWE part code?

### ISSUE THREAD

**Issue by STK2666** [Picsart-AI-Research/StreamingT2V#23]

**Comment by oldnaari** [comment]
Thank you for your interest. We want to notify you that we have just released the codes for Motion Aware Warp Error (MAWE). They are in the [StreamingModelscope](https://github.com/Picsart-AI-Research/StreamingT2V/tree/StreamingModelscope?tab=readme-ov-file) branch. [Here](https://github.com/Picsart-AI-Research/StreamingT2V?tab=readme-ov-file#mawe-motion-aware-warp-error) you can find an example on how to use it.
