### ISSUE TITLE
Are there any plans to release the code of the training pipeline of StreamingT2V?

### ISSUE THREAD

**Issue by AnzeXie** [Picsart-AI-Research/StreamingT2V#5]
Hi, I wonder whether there are any plans on releasing the training pipeline of StreamingT2V? Thank you very much!

**Comment by AnzeXie** [comment]
Hi, I wonder are there any plans to open source the training pipeline of StreamingT2V? Thank you very much!

**Comment by XGGNet** [comment]
+1

**Comment by Mike001-wq** [comment]
+1

**Comment by code-conquer** [comment]
+1

**Comment by Colorfu1** [comment]
+1
