### ISSUE TITLE
StreamingSVD: AttributeError: 'dict' object has no attribute 'embedders'，code error

### ISSUE THREAD

**Issue by wangxihao** [Picsart-AI-Research/StreamingT2V#59]
![image](https://github.com/user-attachments/assets/6ce164f9-1be1-4d5d-b040-e2e6dd682903)

-> embedders = self.conditioner.embedders
AttributeError: 'dict' object has no attribute 'embedders'

**Comment by rob-hen** [comment]
Hi @wangxihao, 

1. We can not replicate the issue
2. Is there anything that you changed in the code? The message indicates that it was not able to construct the embedders  object from the config.yaml file. So either there is something wrong in config.yaml or in the corresponding code to construct the object.

**Comment by wangxihao** [comment]
> Hi @wangxihao,
> 
> 1. We can not replicate the issue
> 2. Is there anything that you changed in the code? The message indicates that it was not able to construct the embedders  object from the config.yaml file. So either there is something wrong in config.yaml or in the corresponding code to construct the object.

I cloned the code from git again and started from scratch. At the very beginning, the following error occurred: RuntimeError: Error(s) in loading state_dict for StreamingSVD:
        Unexpected key(s) in state_dict: "conditioner.embedders.0.
![image](https://github.com/user-attachments/assets/c4b0134b-a603-4a1f-9a62-9037ca3b8927)
and the warning displayed in yellow font is as follows: Warning: Seems object conditioner was not build correct.
so I change 'model.load_state_dict(ckpt)' to 'model.load_state_dict(ckpt, strict=False)' ,
Then a new error happen,   File "/mnt/aiface/workspace-gpu1/wxh/StreamingT2V/code/diffusion_trainer/streaming_svd.py", line 61, in post_init
    embedders = self.conditioner.embedders
AttributeError: 'dict' object has no attribute 'embedders'
still  the warning displayed in yellow font is as follows:
![image](https://github.com/user-attachments/assets/73b2b85f-ecb7-453e-afda-abf8ef7d3fa5)

**Comment by rob-hen** [comment]
HI @wangxihao the main issue I see is that the conditioner object is not created. I cannot reproduce the error.
Nonetheless I created a branch (https://github.com/rob-hen/StreamingT2V_DEBUG_Conditioner), with the only modification of outputting the error message during the conditioner creation. 

Please try that code for further debugging.

**Comment by wangxihao** [comment]
> HI @wangxihao the main issue I see is that the conditioner object is not created. I cannot reproduce the error. Nonetheless I created a branch (https://github.com/rob-hen/StreamingT2V_DEBUG_Conditioner), with the only modification of outputting the error message during the conditioner creation.
> 
> Please try that code for further debugging.

Thank you , I will have a try.

**Comment by rob-hen** [comment]
Looks similar to this issue: https://github.com/Lightning-AI/pytorch-lightning/issues/19999 

Can you post the result of `pip freeze >> requirements.txt` ?

**Comment by wangxihao** [comment]
> Looks similar to this issue: [Lightning-AI/pytorch-lightning#19999](https://github.com/Lightning-AI/pytorch-lightning/issues/19999)
> 
> Can you post the result of `pip freeze >> requirements.txt` ?
Thank you ! as follow:

**Comment by rob-hen** [comment]
Hi @wangxihao, these versions are very different from the versions described in our `requirements.txt`.  Can you ensure the versions are as described there?

**Comment by wangxihao** [comment]
> Hi @wangxihao, these versions are very different from the versions described in our `requirements.txt`. Can you ensure the versions are as described there?

You are so kind! Now it works!Thank you very much.
