### ISSUE TITLE
Error for frames 48 or more

### ISSUE THREAD

**Issue by ajikmr** [Picsart-AI-Research/StreamingT2V#8]
Hello.

Thanks for making code public.

Code works fine for 24 frames (--num_frames=24), but throws error for 48 frames. It happens in class Animation: of utils.iimage.py file.

self.anim_str = self.anim_obj.to_html5_video()

Fix: Default embed_limit=20.0 (in MB). Set it to 1000.0 MB

self.anim_str = self.anim_obj.to_html5_video(embed_limit=1000.0)

OS: Ubuntu22.04
matplotlib.__version__ = '3.8.3'

Thanks.

**Comment by hpoghos** [comment]
Hi @ajikmr 
I wasn't able to reproduce this error, but will add your fix for cases like yours.

Thank you for the detailed issue.

**Comment by oldnaari** [comment]
Fixed excessive memory usage in https://github.com/Picsart-AI-Research/StreamingT2V/pull/16. If this doesn't solve the issue please let us know.
